# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Move
                                 A QGIS plugin
 The Move plugin links MobilityDB to QGIS to visualize moving objects
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-24
        copyright            : (C) 2021 by MobilityDB
        email                : maxime.schoemans@ulb.be
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Move class from file Move.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .move import Move
    return Move(iface)
